### ISSUE TITLE
Does this work anymore?

### ISSUE THREAD

**Issue by Debdut** [sferik/x-cli#459]
https://github.com/sferik/t/issues/458

It seems to me as with lot of problem not being able to authorize, this doesn't work anymore.

**Comment by ebdmuir** [comment]
Works fine for me fwiw

**Comment by rjrobinson** [comment]
Also having an auth issue

**Comment by MHBraun** [comment]
What is the structure of the .trc file?

**Comment by hollerith** [comment]
Structure of two trc with two sets of users

```
---
profiles:
  <username>:
    <consumer_key>:
      username: <username>
      consumer_key: <consumer_key>
      consumer_secret: <consumer_secret>
      token: <api_token>
      secret: <api_secret>
  <second_user>:
    <second_user_key>:
      username: <second_user>
      consumer_key: <second_user_key>
      consumer_secret: <second_user_secret>
      token: <second_api_token>
      secret: <second_api_secret>
configuration:
  default_profile:
  - <username>
  - <consumer_key>
  shitposter:
  - <second_user>
  - <second_user_key>
```
